# Generated by Django 4.2.14 on 2024-08-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_device_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='house',
            name='longitude',
        ),
    ]
